export const menuItems = [
  {
    id: 1,
    title: 'Greek salad',
    category: 'main',
    type: 'salad',
    rating: 4.7,
    price: 250,
    slug: 'greek-salad',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/greek_salad_thumb.jpg',
    img: '/assets/images/foods/greek_salad.jpg',
  },
  {
    id: 2,
    title: 'bruchetta',
    category: 'main',
    img: '/assets/images/foods/bruchetta.jpg',
    type: 'appetizer',
    rating: 4.3,
    price: 150,
    slug: 'bruchetta',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/bruchetta_thumb.jpg',
  },
  {
    id: 3,
    title: 'Lemon Dessert',
    category: 'main',
    thumbnailUrl: '/assets/images/foods/lemon_dessert_thumb.jpg',
    type: 'dessert',
    rating: 4.5,
    price: 200,
    slug: 'lemon-dessert',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    img: '/assets/images/foods/lemon_dessert.jpg',
  },
  {
    id: 4,
    title: 'pizza',
    category: 'main',
    type: 'pizza',
    rating: 4.0,
    price: 300,
    img: '/assets/images/foods/pizza.jpg',
    slug: 'pizza',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/pizza_thumb.jpg',
  },
  {
    id: 5,
    title: 'coffee',
    category: 'coffee',
    type: 'drink',
    rating: 4.2,
    price: 100,
    img: '/assets/images/foods/coffee.jpg',
    slug: 'coffee',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/coffee_thumb.jpg',
  },
  {
    id: 6,
    title: 'mixed shake',
    category: 'drink',
    type: 'shake',
    rating: 4.6,
    price: 120,
    img: '/assets/images/foods/mixed_shake.jpg',
    slug: 'mixed-shake',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/mixed_shake_thumb.jpg',
  },
  {
    id: 7,
    title: 'strawberry shake',
    category: 'drink',
    type: 'shake',
    rating: 4.8,
    price: 150,
    img: '/assets/images/foods/strawberry_shake.jpg',
    slug: 'strawberry-shake',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/strawberry_shake_thumb.jpg',
  },
  {
    id: 8,
    title: 'maggi',
    category: 'main',
    type: 'pasta',
    rating: 4.4,
    price: 80,
    img: '/assets/images/foods/maggi.jpg',
    slug: 'maggi',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/maggi_thumb.jpg',
  },
  {
    id: 9,
    title: 'meal',
    category: 'meal',
    type: 'meal',
    rating: 4.9,
    price: 200,
    img: '/assets/images/foods/meal.jpg',
    slug: 'meal',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/meal_thumb.jpg',
  },
  {
    id: 10,
    title: 'pasta',
    category: 'main',
    type: 'pasta',
    rating: 4.2,
    price: 180,
    img: '/assets/images/foods/pasta.jpg',
    slug: 'pasta',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/pasta_thumb.jpg',
  },
  {
    id: 11,
    title: 'Roasted Vegetable',
    category: 'main',
    type: 'sandwich',
    rating: 4.5,
    price: 120,
    img: '/assets/images/foods/roasted_vegetable.jpg',
    slug: 'roasted-vegetable',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/roasted_vegetable_thumb.jpg',
  },
  {
    id: 12,
    title: 'Caprese',
    category: 'main',
    type: 'sandwich',
    rating: 4.4,
    price: 140,
    img: '/assets/images/foods/caprese.jpg',
    slug: 'caprese',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/caprese_thumb.jpg',
  },
  {
    id: 13,
    title: 'veggie',
    category: 'main',
    type: 'veggie',
    rating: 4.3,
    price: 140,
    img: '/assets/images/foods/veggie.jpg',
    slug: 'veggie',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/veggie_thumb.jpg',
  },
  {
    id: 14,
    title: 'chocolate shake',
    category: 'drink',
    type: 'shake',
    rating: 4.7,
    price: 130,
    img: '/assets/images/foods/chocolate_shake.jpg',
    slug: 'chocolate-shake',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/chocolate_shake_thumb.jpg',
  },
  {
    id: 15,
    title: 'Pork Grilled',
    category: 'main',
    type: 'meat',
    rating: 4.7,
    price: 50,
    img: '/assets/images/foods/pork_grilled.jpg',
    slug: 'pork grilled',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
    thumbnailUrl: '/assets/images/foods/pork_grilled_thumb.jpg',
  },
];
